"""Adda mere collums på tablsa cars og Service.

Revision ID: dacef95a9a7b
Revises: ea3ecd9674b0
Create Date: 2024-02-07 10:31:15.987849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacef95a9a7b'
down_revision = 'ea3ecd9674b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=False))
        batch_op.drop_column('type')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))
        batch_op.drop_column('homeAddress')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mechanic', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('customer', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('customer')
        batch_op.drop_column('mechanic')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeAddress', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('address')

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('owner')
        batch_op.drop_column('sold')
        batch_op.drop_column('available')
        batch_op.drop_column('price')
        batch_op.drop_column('color')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
