"""Per august tweak på database

Revision ID: ea3ecd9674b0
Revises: f12c7f71b7b9
Create Date: 2024-02-07 10:16:30.481684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3ecd9674b0'
down_revision = 'f12c7f71b7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('eier2')
        batch_op.drop_column('eier1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eier1', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('eier2', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
