"""Added Client and User tables. Fixed Service table

Revision ID: f12c7f71b7b9
Revises: 8df36847298b
Create Date: 2024-02-05 10:48:02.967827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12c7f71b7b9'
down_revision = '8df36847298b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('phoneNumber', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('epost', sa.String(), nullable=False),
    sa.Column('homeAddress', sa.String(), nullable=False),
    sa.Column('postnumber', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('phoneNumber')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phoneNumber', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('zipcode')
        batch_op.drop_column('address')
        batch_op.drop_column('tlf')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=False))

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tlf', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('zipcode', sa.VARCHAR(), nullable=False))

    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
